### ISSUE TITLE
Fewer sequences left after filtering than the batch size

### ISSUE THREAD

**Issue by barbarashih** [RasmussenLab/vamb#103]
Hi,
I got this error message when I ran vamb on my dataset
`vamb -o SEP --outdir $OUT_DIR --fasta $CONCAT_FASTA --bamfiles $IN_BAM_DIR/*.bam -o C
`

Error
```
Traceback (most recent call last):
  File "/exports/eddie/scratch/bshih/amr_virome/conda/vamb/bin/vamb", line 11, in <module>
    sys.exit(main())
  File "/exports/eddie/scratch/bshih/amr_virome/conda/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 528, in main
    logfile=logfile)
  File "/exports/eddie/scratch/bshih/amr_virome/conda/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 251, in run
    dropout, cuda, batchsize, nepochs, lrate, batchsteps, logfile)
  File "/exports/eddie/scratch/bshih/amr_virome/conda/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 140, in trainvae
    destroy=True, cuda=cuda)
  File "/exports/eddie/scratch/bshih/amr_virome/conda/vamb/lib/python3.7/site-packages/vamb/encode.py", line 74, in make_dataloader
    raise ValueError('Fewer sequences left after filtering than the batch size.')
ValueError: Fewer sequences left after filtering than the batch size.
```
I am wondering if there are additional settings I need to make?

Thanks
Barbara

**Comment by simonrasmu** [comment]
Dear Barbara,

It looks like all your contigs got filtered away. VAMB by default removes contigs smaller than 2,000bp. Did you input contigs/sequences shorter than this?

Best,

Simon

**Comment by barbarashih** [comment]
Hi Simon,
Yes I did. Should I filter them before input them to VAMB?

Thanks
BW

Barbara

**Comment by simonrasmu** [comment]
VAMB will normally remove all contigs smaller than 2,000 bp. What the error message above means is that it remove all (or almost all) contigs when parsing the data. Can you check that your input contigs are larger than 2,000bp?

**Comment by barbarashih** [comment]
I used concatenate.py to combine the contigs from all samples, and that seem to have only kept contigs larger than 2,000bp. My input contigs are all larger than 2,000 bp.

**Comment by barbarashih** [comment]
Thank you, that really helped. I made an error in an earlier step which means my bam files were empty/only has header.
