### ISSUE TITLE
vamb and cuda

### ISSUE THREAD

**Issue by alienzj** [RasmussenLab/vamb#111]
Dear vamb developer,

I run vamb with cuda support on my school SLURM system.
The GPU nodes allow the task to run for up to a week, but I found that vamb took 2 days to run to epoch 50, is there any way to speed it up?

Best, thanks,
Jie

**Comment by jakobnissen** [comment]
Dear @alienzj 

That's surprising. Vamb is pretty fast. For comparison, with 200,000 contigs, it takes approx. 5 minutes to run 300 epochs on our compute cluster with a Tesla V100 GPU.

How many contigs do you have (it says so in the Vamb log file), and which GPU is it running on? Furthermore, which version of Vamb and PyTorch are you using?

This might be a case of #27 , which we never explained.

**Comment by alienzj** [comment]
Dear @jakobnissen,
I also think vamb should be pretty fast.

Bellow is the log:
```
Starting Vamb version 3.0.3
        Date and time is 2022-04-21 10:23:59.394892

Loading TNF
        Minimum sequence length: 2000
        Loading data from FASTA file results/06.multisplit_binning/scaftigs/PRJEB32631_Shao.megahit.combined.out/PRJEB32631_Shao.megahit.combined.scaftigs.fa.gz

        Kept 45979998278 bases in 4892087 sequences
        Processed TNF in 1258.23 seconds

Loading RPKM
        Reference hash: ca9fda51c581fa9531c618e4181df0e4
        Loading RPKM from JGI file results/06.multisplit_binning/matrix/PRJEB32631_Shao.megahit.align2combined_scaftigs.jgi.abundance.matrix.tsv
        Processed RPKM in 3471.53 seconds

Creating and training VAE
        Created VAE
        Created dataloader and mask
        Number of sequences unsuitable for encoding: 0
        Number of sequences remaining: 4892087

        Network properties:
        CUDA: True
        Alpha: 0.15
        Beta: 200.0
        Dropout: 0.2
        N hidden: 512, 512
        N latent: 32

        Training properties:
        N epochs: 500
        Starting batch size: 256
        Batchsteps: 25, 75, 150, 300
        Learning rate: 0.001
        N sequences: 4892087
        N samples: 1679

        Epoch: 1        Loss: 0.566813  CE: 4.3894704   SSE: 32.747168  KLD: 106.8109   Batchsize: 256
        Epoch: 2        Loss: 0.544053  CE: 4.2058835   SSE: 31.345492  KLD: 108.6989   Batchsize: 256
        Epoch: 3        Loss: 0.539990  CE: 4.1744320   SSE: 30.990483  KLD: 109.0445   Batchsize: 256
        Epoch: 4        Loss: 0.537813  CE: 4.1571199   SSE: 30.808635  KLD: 109.4927   Batchsize: 256
        Epoch: 5        Loss: 0.536350  CE: 4.1455692   SSE: 30.678529  KLD: 109.8037   Batchsize: 256
        Epoch: 6        Loss: 0.535333  CE: 4.1373129   SSE: 30.601457  KLD: 110.0624   Batchsize: 256
        Epoch: 7        Loss: 0.534573  CE: 4.1311042   SSE: 30.542668  KLD: 110.2931   Batchsize: 256
        Epoch: 8        Loss: 0.533978  CE: 4.1260325   SSE: 30.510686  KLD: 110.4974   Batchsize: 256
 ```

**Comment by alienzj** [comment]
GPU information and torch, vamb version:
```
➤ /usr/bin/cat  ~/toolkit/metapi_dev/test/test_coassembly_by_group/check_GPU.log                                                                                                                                                        (base) 
Mon Apr 18 10:35:46 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.27.04    Driver Version: 460.27.04    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:89:00.0 Off |                    0 |
| N/A   24C    P0    38W / 300W |      0MiB / 32510MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
 
/home/jiezhu/.conda/envs/d10d24418d44aee2b71e49d9f8a08250/bin/python
 
torch version: 1.11.0
torch file: /home/jiezhu/.conda/envs/d10d24418d44aee2b71e49d9f8a08250/lib/python3.8/site-packages/torch/__init__.py
vamb version: (3, 0, 3)
vamb file: /home/jiezhu/.conda/envs/d10d24418d44aee2b71e49d9f8a08250/lib/python3.8/site-packages/vamb/__init__.py
True
/home/jiezhu/.conda/envs/d10d24418d44aee2b71e49d9f8a08250/bin/vamb
```

**Comment by simonrasmu** [comment]
Hi Jie, are you sure Vamb is using the GPUs when on the node? You can try to run nvidia-smi on the node while it is running Vamb training (e.g. Epoch 1, epoch 2 etc) and see if the job appears. If it doesn't it means that it is not using it

**Comment by alienzj** [comment]
> Hi Jie, are you sure Vamb is using the GPUs when on the node? You can try to run nvidia-smi on the node while it is running Vamb training (e.g. Epoch 1, epoch 2 etc) and see if the job appears. If it doesn't it means that it is not using it

I am sure Vamb is using the GPUs when on the node. I set the parameter "--cuda" and Vamb also found GPU, you can see it at the above vamb's log.
From above GPU log, it is a log file that I checked whether PyTorch can run at GPU node.

**Comment by alienzj** [comment]
> I'm honestly not sure how to help you with this. Your GPU is fast enough, and 5 mill contigs on 1679 samples is not too bad. This should complete in a few hours. Is PyTorch in general slow for you? It could be a CUDA driver issue, but it's hard for me to tell. I'll leave the issue up. Sorry I can't help you.

I am not sure PyTorch in general is slow for me. I need to test it.
Anyway, thanks for your help ~

**Comment by alienzj** [comment]
Dear vamb developer, 

Our school HPC administrator guess that the job keep moving data back-and-fro under that limited memory footprint, spending most of the time during I/O (instead of GPU or even CPU usage). They told me to increase the memory usage for per CPU at SLURM system. After adding parameter "--mem-per-cpu=10000M" in the SLURM script, the running speed is obviously much faster, the log recored that trained VAE and encoded in 19058.47 seconds for 500 epoch.

But at the clustering step, the job failed:
```
Traceback (most recent call last):
  File "/home/jiezhu/.conda/envs/vamb_cuda11.2/bin/vamb", line 8, in <module>
    sys.exit(main())
  File "/home/jiezhu/.conda/envs/vamb_cuda11.2/lib/python3.10/site-packages/vamb/__main__.py", line 501, in main
    run(args.outdir,
  File "/home/jiezhu/.conda/envs/vamb_cuda11.2/lib/python3.10/site-packages/vamb/__main__.py", line 260, in run
    cluster(clusterspath, latent, contignames, windowsize, minsuccesses, maxclusters,
  File "/home/jiezhu/.conda/envs/vamb_cuda11.2/lib/python3.10/site-packages/vamb/__main__.py", line 188, in cluster
    _ = vamb.vambtools.write_clusters(clustersfile, renamed, max_clusters=maxclusters,
  File "/home/jiezhu/.conda/envs/vamb_cuda11.2/lib/python3.10/site-packages/vamb/vambtools.py", line 335, in write_clusters
    for clustername, contigs in clusters:
  File "/home/jiezhu/.conda/envs/vamb_cuda11.2/lib/python3.10/site-packages/vamb/vambtools.py", line 653, in _binsplit_generator
    for binname, headers in cluster_iterator:
  File "/home/jiezhu/.conda/envs/vamb_cuda11.2/lib/python3.10/site-packages/vamb/__main__.py", line 181, in <genexpr>
    renamed = ((str(i+1), c) for (i, (n,c)) in enumerate(it))
  File "/home/jiezhu/.conda/envs/vamb_cuda11.2/lib/python3.10/site-packages/vamb/cluster.py", line 458, in cluster
    for cluster in it:
  File "/home/jiezhu/.conda/envs/vamb_cuda11.2/lib/python3.10/site-packages/vamb/cluster.py", line 197, in __next__
    cluster, medoid, points = self._findcluster()
  File "/home/jiezhu/.conda/envs/vamb_cuda11.2/lib/python3.10/site-packages/vamb/cluster.py", line 228, in _findcluster
    medoid, distances = _wander_medoid(self.matrix, self.kept_mask, self.seed, self.MAXSTEPS, self.RNG, self.CUDA)
  File "/home/jiezhu/.conda/envs/vamb_cuda11.2/lib/python3.10/site-packages/vamb/cluster.py", line 409, in _wander_medoid
    cluster, distances, average_distance = _sample_medoid(matrix, kept_mask, medoid, _MEDOID_RADIUS, cuda)
  File "/home/jiezhu/.conda/envs/vamb_cuda11.2/lib/python3.10/site-packages/vamb/cluster.py", line 391, in _sample_medoid
    distances = _calc_distances(matrix, medoid)
  File "/home/jiezhu/.conda/envs/vamb_cuda11.2/lib/python3.10/site-packages/vamb/cluster.py", line 380, in _calc_distances
    dists = 0.5 - matrix.matmul(matrix[index])
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemv(handle, op, m, n, &alpha, a, lda, x, incx, &beta, y, incy)`
```
Could you please help me to figure out the problem ?
Thanks very much!

**Comment by jakobnissen** [comment]
Dear @alienzj 
Thanks for troubleshooting the slowness issue - we've recently reached the same conclusion in #27.
With regard to the new error, this looks like some internal error in your CUDA library, and not something in Vamb. I would try googling for the bottom error (the one with `CUBLAD_STATUS_INVALID_VALUE`).

**Comment by alienzj** [comment]
Dear vamb developer,
The CUDA issue was fixed when I  use CUDA installed by my school HPC adminstrator.
I also found the below software combination can work well by snakemake-conda workflow:
```
channels:
  - pytorch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pytorch =*=*cuda112*
  - torchvision 
  - cudatoolkit =11.2
  - pysam
  - pip
  - pip: 
     - git+https://github.com/RasmussenLab/vamb@v3.0.7
  ```

And I also integrated the vamb with [metapi](https://github.com/ohmeta/metapi/blob/dev/metapi/rules/binning_multisplit.smk#L346) based on vamb workflow implemation, so that we can generate MAGs from reads. 

For SLURM run, the configuration can see [here](https://github.com/ohmeta/metapi/blob/dev/metapi/profiles/slurm/cluster.yaml#L305), like below:
```
binning_vamb:
  partition: "gpu"
  qos: "gpu"
  gres: "gpu:1" # Thank Juilian and Bill of HKU-HPC
  mem: "24G"
```

So far, the problem is solved. Thank all!
