### ISSUE TITLE
ValueError: could not convert string to float: 'contigLen'

### ISSUE THREAD

**Issue by Adarsh931** [RasmussenLab/vamb#118]
I am running VAMB on 447 samples. I was following the snakemake workflow but each step separately due to the time limit on the server. I am getting this error:

```
Traceback (most recent call last):
  File "/gpfs/ysm/project/christakis/as4258/conda_envs/vamb/bin/vamb", line 8, in <module>
    sys.exit(main())
  File "/gpfs/ysm/project/christakis/as4258/conda_envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 530, in main
    logfile=logfile)
  File "/gpfs/ysm/project/christakis/as4258/conda_envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 249, in run
    len(tnfs), minalignscore, minid, subprocesses, logfile)
  File "/gpfs/ysm/project/christakis/as4258/conda_envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 101, in calc_rpkm
    rpkms = vamb.vambtools._load_jgi(file, mincontiglength, refhash)
  File "/gpfs/ysm/project/christakis/as4258/conda_envs/vamb/lib/python3.7/site-packages/vamb/vambtools.py", line 598, in _load_jgi
    if float(fields[1]) < minlength:
ValueError: could not convert string to float: 'contigLen'
Thu May 19 13:11:49 EDT 2022
slurmstepd: error: get_addr_info: getaddrinfo() failed: Name or service not known
slurmstepd: error: slurm_set_addr: Unable to resolve "scheduler.farnam.hpc.yale.internal"
slurmstepd: error: Unable to establish control machine address
slurmstepd: error: get_addr_info: getaddrinfo() failed: Name or service not known
slurmstepd: error: slurm_set_addr: Unable to resolve "scheduler.farnam.hpc.yale.internal"
slurmstepd: error: Unable to establish control machine address
slurmstepd: error: get_addr_info: getaddrinfo() failed: Name or service not known
slurmstepd: error: slurm_set_addr: Unable to resolve "scheduler.farnam.hpc.yale.internal"
slurmstepd: error: Unable to establish control machine address
```

**Comment by simonrasmu** [comment]
Do you have the header line twice in the file? It says it cannot convert "contigLen" to a float (which makes sense as it is text and thus cannot be converted to a number). "contigLen" is normally in the header of the jgi file.

**Comment by Adarsh931** [comment]
I just checked, and I have only one header line.

**Comment by simonrasmu** [comment]
You are sure there are no extra headers further down in the input-file or whether there is an empty line in the beginning? The code assumes the first line is a header and then all subsequent 2nd fields (tab-separated) are numbers. It dies because it finds a string (contgLen) in a line that is not the first one.

**Comment by Adarsh931** [comment]
I checked just now, and yes, I found there are multiple "contigLen". I am a recreating the abundance file. Hopefully that would solve the problem. Thank you so much!
