### ISSUE TITLE
Keep getting Error: Last batch size exceeds dataset length

### ISSUE THREAD

**Issue by bellasmith121995** [RasmussenLab/vamb#120]
I ran all my datasets the same way and one dataset keeps getting this error, while the others ran perfectly:

Traceback (most recent call last):
  File "/fs/project/miniconda3/envs/vamb/bin/vamb", line 11, in <module>
    sys.exit(main())
  File "/fs/project/miniconda3/envs/vamb/lib/python3.6/site-packages/vamb/__main__.py", line 528, in main
    logfile=logfile)
  File "/fs/project/miniconda3/envs/vamb/lib/python3.6/site-packages/vamb/__main__.py", line 251, in run
    dropout, cuda, batchsize, nepochs, lrate, batchsteps, logfile)
  File "/fs/project/miniconda3/envs/vamb/lib/python3.6/site-packages/vamb/__main__.py", line 150, in trainvae
    logfile=logfile, modelfile=modelpath)
  File "/fs/project/miniconda3/envs/vamb/lib/python3.6/site-packages/vamb/encode.py", line 466, in trainmodel
    raise ValueError('Last batch size exceeds dataset length')
ValueError: Last batch size exceeds dataset length

Any ideas?

**Comment by jakobnissen** [comment]
See #117, #103, #59
