### ISSUE TITLE
Error occurs when installation version 3.0.8

### ISSUE THREAD

**Issue by liangjinsong** [RasmussenLab/vamb#125]
Hi, when I installed the version 3.0.8 according to the following steps, error occurred. Could you help find the reason? Thanks!

---------commands for install----------
git clone https://github.com/RasmussenLab/vamb -b master
cd vamb
pip3 install -e .
------------------------------------------

------------------error received------------------------
jinsong@HUAWEI:~/software/vamb$ pip3 --version
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

jinsong@HUAWEI:~/software/vamb$ pip3 install -e .
Obtaining file:///home/jinsong/software/vamb
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/jinsong/software/vamb/setup.py'"'"'; __file__='"'"'/home/jinsong/software/vamb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /home/jinsong/software/vamb/
    Complete output (51 lines):
    running egg_info
    creating vamb.egg-info
    writing vamb.egg-info/PKG-INFO
    writing dependency_links to vamb.egg-info/dependency_links.txt
    writing entry points to vamb.egg-info/entry_points.txt
    writing requirements to vamb.egg-info/requires.txt
    writing top-level names to vamb.egg-info/top_level.txt
    writing manifest file 'vamb.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/jinsong/software/vamb/setup.py", line 35, in <module>
        setup(**SETUP_METADATA)
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 297, in run
        self.find_sources()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 304, in find_sources
        mm.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 535, in run
        self.add_defaults()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 571, in add_defaults
        sdist.add_defaults(self)
      File "/usr/lib/python3.8/distutils/command/sdist.py", line 226, in add_defaults
        self._add_defaults_python()
      File "/usr/lib/python3/dist-packages/setuptools/command/sdist.py", line 135, in _add_defaults_python
        build_py = self.get_finalized_command('build_py')
      File "/usr/lib/python3.8/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/usr/lib/python3.8/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/usr/lib/python3/dist-packages/setuptools/command/build_py.py", line 34, in finalize_options
        orig.build_py.finalize_options(self)
      File "/usr/lib/python3.8/distutils/command/build_py.py", line 43, in finalize_options
        self.set_undefined_options('build',
      File "/usr/lib/python3.8/distutils/cmd.py", line 286, in set_undefined_options
        src_cmd_obj = self.distribution.get_command_obj(src_cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 857, in get_command_obj
        klass = self.get_command_class(command)
      File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 834, in get_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
        return self.resolve()
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ModuleNotFoundError: No module named 'setuptools.command.build'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    ----------------------------------------

**Comment by liangjinsong** [comment]
I have resolved this issue by running the two following commands.
python3 -m pip install --upgrade pip setuptools wheel
pip install https://github.com/RasmussenLab/vamb/archive/v3.0.8.zip
