### ISSUE TITLE
Error while writing clusters 

### ISSUE THREAD

**Issue by blindner6** [RasmussenLab/vamb#148]
When recently running VAMB (4.0.0) I received the following error and VAMB quit with the `vae_clusters.tsv` table empty. 

```Traceback (most recent call last):
  File "/storage/home/hcoda1/4/blindner6/.conda/envs/vamb-2/bin/vamb", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/storage/home/hcoda1/4/blindner6/.conda/envs/vamb-2/lib/python3.11/site-packages/vamb/__main__.py", line 1369, in main
    run(
  File "/storage/home/hcoda1/4/blindner6/.conda/envs/vamb-2/lib/python3.11/site-packages/vamb/__main__.py", line 824, in run
    cluster(
  File "/storage/home/hcoda1/4/blindner6/.conda/envs/vamb-2/lib/python3.11/site-packages/vamb/__main__.py", line 656, in cluster
    clusternumber, ncontigs = vamb.vambtools.write_clusters(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/storage/home/hcoda1/4/blindner6/.conda/envs/vamb-2/lib/python3.11/site-packages/vamb/vambtools.py", line 373, in write_clusters
    for clustername, contigs in clusters:
  File "/storage/home/hcoda1/4/blindner6/.conda/envs/vamb-2/lib/python3.11/site-packages/vamb/vambtools.py", line 647, in binsplit
    for binname, headers in clusters:
  File "/storage/home/hcoda1/4/blindner6/.conda/envs/vamb-2/lib/python3.11/site-packages/vamb/__main__.py", line 640, in <genexpr>
    renamed = (
              ^
  File "/storage/home/hcoda1/4/blindner6/.conda/envs/vamb-2/lib/python3.11/site-packages/vamb/cluster.py", line 260, in __next__
    cluster, _, points = self._findcluster()
                         ^^^^^^^^^^^^^^^^^^^
  File "/storage/home/hcoda1/4/blindner6/.conda/envs/vamb-2/lib/python3.11/site-packages/vamb/cluster.py", line 293, in _findcluster
    medoid, distances = _wander_medoid(
                        ^^^^^^^^^^^^^^^
  File "/storage/home/hcoda1/4/blindner6/.conda/envs/vamb-2/lib/python3.11/site-packages/vamb/cluster.py", line 532, in _wander_medoid
    sampled_medoid = int(rng.choice(cluster).item())
                         ^^^^^^^^^^^^^^^^^^^
  File "/storage/home/hcoda1/4/blindner6/.conda/envs/vamb-2/lib/python3.11/random.py", line 369, in choice
    if not seq:
RuntimeError: Boolean value of Tensor with more than one value is ambiguous
```

I've installed VAMB via pip install. I also checked that my concatenated contig set was renamed with an appropriate delimiting strategy (with 'C' as the delimiter just to keep things contiguous with your usage guide). Mapping was done with bwa-mem and then sorted BAMs were provided to VAMB. My call to VAMB was: `vamb --outdir ${outdir} --fasta ${assembly} --bamfiles ${indir}/*.bam -o C`

Wondering whether you have any immediate guidance based on the above. Thanks so much.

**Comment by madscort** [comment]
I just encountered the same error, bam files were created exactly as in the GitHub provided avamb snakemake workflow.

**Comment by jakobnissen** [comment]
I found the issue. Vamb is not compatible with Python 3.11, since 3.11 changed the definition of `Random.choice`.
The short-term fix is to use Python 3.10 or below, but I'll get a fix pushed that makes it work with Python3.11
