### ISSUE TITLE
KeyError: "Separator 'C' not in sequence label

### ISSUE THREAD

**Issue by rzhan186** [RasmussenLab/vamb#173]
Dear Vamb developers, 

I came across an error while running Vamb using GPUs. The first stage of the running processes seems to have finished successfully, as no error message was shown in the log file. However, the system returned the following error. I've attached the error message and the log file below, could you have me troubleshoot? 
```
Traceback (most recent call last):
  File "/home/ruizhang/.local/bin/vamb", line 33, in <module>
    sys.exit(load_entry_point('vamb', 'console_scripts', 'vamb')())
  File "/project/6004066/ruizhang/software/vamb/vamb/__main__.py", line 1390, in main
    run(
  File "/project/6004066/ruizhang/software/vamb/vamb/__main__.py", line 831, in run
    cluster(
  File "/project/6004066/ruizhang/software/vamb/vamb/__main__.py", line 663, in cluster
    clusternumber, ncontigs = vamb.vambtools.write_clusters(
  File "/project/6004066/ruizhang/software/vamb/vamb/vambtools.py", line 373, in write_clusters
    for clustername, contigs in clusters:
  File "/project/6004066/ruizhang/software/vamb/vamb/vambtools.py", line 643, in binsplit
    for newbinname, splitheaders in _split_bin(binname, headers, separator):
  File "/project/6004066/ruizhang/software/vamb/vamb/vambtools.py", line 618, in _split_bin
    raise KeyError(f"Separator '{separator}' not in sequence label: '{header}'")
KeyError: "Separator 'C' not in sequence label: 'HX_surface_000000057877'"
```
 
[log.txt](https://github.com/RasmussenLab/vamb/files/11522502/log.txt)

Thank you for your help!

**Comment by jakobnissen** [comment]
Dear @rzhan186 

You seem to have run it with `-o C` set. This option will "split" your bins by the string `"C"`. See point 3 in the [recommended workflow](https://github.com/RasmussenLab/vamb#recommended-workflow).
The solution is to either run Vamb without the `-o C` option, or to use the shipped script `src/concatate.py` to rename your sequence to the format `f"S{sample_number}C{contig_number}"`.

Closing as solved. You're welcome to re-open.

**Comment by rzhan186** [comment]
Dear Jakob, 

Thank you for the solution! It indeed worked after removing the `-o C` option!

Best,
Rui
