### ISSUE TITLE
cuDNN error for vamb v2.0.1

### ISSUE THREAD

**Issue by yanhui09** [RasmussenLab/vamb#19]
Thanks a lot for fantastic binner.
I met a error of using cuda when switching from version 1 to version 2.1.0.
For the previous version, it works fine on my RTX 2080 using cuda 10.0 and cudnn 7.3.1(also works with newest cudnn 7.6.0).
However it doesn't work with the same cuda dependence (cuda=10.0, cudnn=7.3.1/7.6.0) for version 2.1.0. The error log was listed blow. (some problems with batch_norm in pytorch?)
 
Traceback (most recent call last):
  File "/home/yanhui/anaconda3/bin/vamb", line 11, in <module>
    load_entry_point('vamb', 'console_scripts', 'vamb')()
  File "/home/yanhui/Data/depot_tool/vamb_2.0.1/vamb/vamb/__main__.py", line 452, in main
    logfile=logfile)
  File "/home/yanhui/Data/depot_tool/vamb_2.0.1/vamb/vamb/__main__.py", line 215, in run
    dropout, cuda, batchsize, nepochs, lrate, batchsteps, logfile)
  File "/home/yanhui/Data/depot_tool/vamb_2.0.1/vamb/vamb/__main__.py", line 150, in trainvae
    logfile=logfile, modelfile=modelpath)
  File "/home/yanhui/Data/depot_tool/vamb_2.0.1/vamb/vamb/encode.py", line 484, in trainmodel
    dataloader = self.trainepoch(dataloader, epoch, optimizer, batchsteps_set, logfile)
  File "/home/yanhui/Data/depot_tool/vamb_2.0.1/vamb/vamb/encode.py", line 301, in trainepoch
    depths_out, tnf_out, mu, logsigma = self(depths_in, tnf_in)
  File "/home/yanhui/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yanhui/Data/depot_tool/vamb_2.0.1/vamb/vamb/encode.py", line 251, in forward
    mu, logsigma = self._encode(tensor)
  File "/home/yanhui/Data/depot_tool/vamb_2.0.1/vamb/vamb/encode.py", line 208, in _encode
    tensor = encodernorm(self.dropoutlayer(self.relu(encoderlayer(tensor))))
  File "/home/yanhui/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yanhui/anaconda3/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 83, in forward
    exponential_average_factor, self.eps)
  File "/home/yanhui/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py", line 1697, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

**Comment by yanhui09** [comment]
vamb pip-installation was outside my conda environment while torch was installed there. LoL
I pip-install within the conda environment. It works smoothly.Thanks☺
