### ISSUE TITLE
avamb snakemake pipeline error in run_vamb

### ISSUE THREAD

**Issue by SebastianDall** [RasmussenLab/vamb#200]
Hello Jakob

I am having trouble running the avamb snakemake pipeline.

Firstly, I had an issue in the `bam_abundance` rule where I received a "missing positional argument" in the py_runcoverm from parsebam.py. I fixed it (I hope) by supplying none as default. I have made a pull request, since the pipeline continued after this change.

However in the next rule run_vamb I received another error:
```python
Traceback (most recent call last):
  File ".conda/envs/avamb/bin/vamb", line 33, in <module>
    sys.exit(load_entry_point('vamb', 'console_scripts', 'vamb')())
  File "vamb/vamb/__main__.py", line 1390, in main
    run(
  File "vamb/vamb/__main__.py", line 831, in run
    cluster(
  File "vamb/vamb/__main__.py", line 637, in cluster
    cluster_generator = vamb.cluster.ClusterGenerator(
TypeError: __init__() got an unexpected keyword argument 'seed'

```

I tried to run the rule manually with the same result:
```bash
(avamb) vamb --outdir avamb_outdir/avamb --fasta avamb_outdir/contigs.flt.fna.gz -p 20 --rpkm avamb_outdir/abundance.npz -m 2000 --minfasta 200000    --model vae-aae  -o C  --seed 0
```

I looked at the vamb.cluster.ClusterGenerator source code and couldn't find a seed argument, so I commented it out:
```python vamb/__main__.py line 631
cluster_generator = vamb.cluster.ClusterGenerator(
        latent,
        windowsize=cluster_options.window_size,
        minsuccesses=cluster_options.min_successes,
        destroy=True,
        normalized=False,
        cuda=vamb_options.cuda,
        # seed=vamb_options.seed,
    )
```

And tried running it again. The next error was:
```python
Traceback (most recent call last):
  File ".conda/envs/avamb/bin/vamb", line 33, in <module>
    sys.exit(load_entry_point('vamb', 'console_scripts', 'vamb')())
  File "vamb/vamb/__main__.py", line 1390, in main
    run(
  File "vamb/vamb/__main__.py", line 831, in run
    cluster(
  File "vamb/vamb/__main__.py", line 637, in cluster
    cluster_generator = vamb.cluster.ClusterGenerator(
TypeError: __init__() missing 1 required positional argument: 'lengths'
```

At this point I am lost. I can see a file in avamb_outdir/avamb/lengths.npz, but I am unsure what to do with it.

I have tried on both my own samples and the example data with the same result. I have also tried reinstalling everything. I could use some help please.

Best,
Sebastian

**Comment by jakobnissen** [comment]
Dear @SebastianDall 

Thanks for the bug report. This is fixed in #201, which will be merged shortly.

**Comment by SebastianDall** [comment]
Awesome! Thanks a lot.
