### ISSUE TITLE
Inconsistency between compositionMetaData and refs in BAM files

### ISSUE THREAD

**Issue by EmmettPeng** [RasmussenLab/vamb#281]
Hi,

After getting the bam files as instructions, I intended to run vamb using default settings and it reports error:
```
Traceback (most recent call last):
  File "/home/pengxi/.conda/envs/vamb/bin/vamb", line 33, in <module>
    sys.exit(load_entry_point('vamb', 'console_scripts', 'vamb')())
  File "/home/pengxi/softwares/vamb/vamb/__main__.py", line 1390, in main
    run(
  File "/home/pengxi/softwares/vamb/vamb/__main__.py", line 751, in run
    abundance = calc_rpkm(
  File "/home/pengxi/softwares/vamb/vamb/__main__.py", line 485, in calc_rpkm
    abundance = vamb.parsebam.Abundance.from_files(
  File "/home/pengxi/softwares/vamb/vamb/parsebam.py", line 135, in from_files
    (matrix, refhash) = cls.run_pycoverm(
  File "/home/pengxi/softwares/vamb/vamb/parsebam.py", line 218, in run_pycoverm
    raise ValueError(
ValueError: CompositionMetaData was created with 977484 sequences, but number of refs in BAM files are 6025.
```

I have no idea what went wrong.

Emmett

**Comment by jakobnissen** [comment]
Dear @EmmettPeng 

It's saying that the sequences you used to generate the BAM file were different from the contigs you passed to --fasta.
The former has 6025 sequences and the latter close to a million

**Comment by EmmettPeng** [comment]
Oh I found that I pass the original contigs to ``--fasta``. It should have been the catalog file. Thanks for the hint!
