### ISSUE TITLE
*.bam is not sorted by reference

### ISSUE THREAD

**Issue by JiaLonghao1997** [RasmussenLab/vamb#293]
When upgrading VAMB from version 3.0.2 to version 4.1.3, errors that did not appear in the old version appeared.
```
Traceback (most recent call last):
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/vamb/bin/vamb", line 8, in <module>
    sys.exit(main())
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/vamb/lib/python3.10/site-packages/vamb/__main__.py", line 1390, in main
    run(
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/vamb/lib/python3.10/site-packages/vamb/__main__.py", line 751, in run
    abundance = calc_rpkm(
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/vamb/lib/python3.10/site-packages/vamb/__main__.py", line 485, in calc_rpkm
    abundance = vamb.parsebam.Abundance.from_files(
  File "/home1/jialh/tools/anaconda3/envs/mamba/envs/vamb/lib/python3.10/site-packages/vamb/parsebam.py", line 121, in from_files
    raise ValueError(f"Path {path} is not sorted by reference.")
ValueError: Path /public/home/jialh/metaHiC/workdir/Yeast/VAMB/MY_mNGS_megahit/MY_mNGS_megahit.bam is not sorted by reference.

```

**Comment by jakobnissen** [comment]
Dear @JiaLonghao1997 

Vamb 4, unlike Vamb 3, requires your BAM files to be sorted by reference first. This can be done with samtools sort.

Closing this issue as solved, but you're welcome to ask any further questions.
