### ISSUE TITLE
`All batchsteps must be less than nepochs` thrown when running taxometer

### ISSUE THREAD

**Issue by Prunoideae** [RasmussenLab/vamb#358]
Python: 3.10.14
Vamb: 9810ef047ef41f986b7ddcfdd3dc06947ee0ab6c on GitHub

Error message (Edited to print batchsteps and nepochs):
```python
❯ vamb bin taxvamb --cuda --outdir taxbins --bamdir bams --fasta assembly.fa --taxonomy mmseqs-taxa/mmseqs-taxa_lca.tsv
Traceback (most recent call last):
  File "/home/-----/miniconda3/envs/meta/bin/vamb", line 8, in <module>
    sys.exit(main())
  File "/mnt/nvme1n1/public/-----/projects/meta/vamb/vamb/__main__.py", line 2198, in main
    opt = BinTaxVambOptions.from_args(args)
  File "/mnt/nvme1n1/public/-----/projects/meta/vamb/vamb/__main__.py", line 706, in from_args
    taxonomy = RefinableTaxonomyOptions.from_args(args)
  File "/mnt/nvme1n1/public/-----/projects/meta/vamb/vamb/__main__.py", line 448, in from_args
    return cls(TaxometerOptions.from_args(args))
  File "/mnt/nvme1n1/public/-----/projects/meta/vamb/vamb/__main__.py", line 396, in from_args
    BasicTrainingOptions.from_args_taxometer(args),
  File "/mnt/nvme1n1/public/-----/projects/meta/vamb/vamb/__main__.py", line 240, in from_args_taxometer
    return cls(
  File "/mnt/nvme1n1/public/-----/projects/meta/vamb/vamb/__main__.py", line 261, in __init__
    raise argparse.ArgumentTypeError(
argparse.ArgumentTypeError: All batchsteps must be less than nepochs (100), actual batchsteps: [25, 75, 150, 225]
```

Seems that
https://github.com/RasmussenLab/vamb/blob/9810ef047ef41f986b7ddcfdd3dc06947ee0ab6c/vamb/__main__.py#L1844-L1851
https://github.com/RasmussenLab/vamb/blob/9810ef047ef41f986b7ddcfdd3dc06947ee0ab6c/vamb/__main__.py#L1860-L1868
are causing the issue.

May I ask what nepochs (or batchsteps) would be appropriate as a workaround if I want to run taxometer now too?

**Comment by jakobnissen** [comment]
Thanks for the bug report. This is indeed an issue with the default parameters. They will be changed in #359
