### ISSUE TITLE
bam file and fasta header not the same order

### ISSUE THREAD

**Issue by jianshu93** [RasmussenLab/vamb#51]
Hello dear VAMB authors,

I alway have a error saying that fasta header and bam header are not the same order. I do exactly the main GitHub page suggest. Here are the error:

[E::idx_find_and_load] Could not retrieve index file for '/storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/02.megahit/pico552.bam'
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/lib/python3.8/site-packages/vamb/parsebam.py", line 253, in _get_contig_rpkms
    _check_bamfile(inpath, bamfile, refhash, minlength)
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/lib/python3.8/site-packages/vamb/parsebam.py", line 221, in _check_bamfile
    raise ValueError(errormsg.format(path, hash.hex(), refhash.hex()))
ValueError: BAM file /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/02.megahit/pico552.bam has reference hash af5495d3741e8950a887e7803a8c1222, expected 60fdc1d5d6cb902da39e4771abb224a7. Verify that all BAM headers and FASTA headers are identical and in the same order.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/bin/vamb", line 8, in <module>
    sys.exit(main())
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/lib/python3.8/site-packages/vamb/__main__.py", line 499, in main
    run(args.outdir,
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/lib/python3.8/site-packages/vamb/__main__.py", line 246, in run
    rpkms = calc_rpkm(outdir, bampaths, rpkmpath, jgipath, mincontiglength, refhash,
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/lib/python3.8/site-packages/vamb/__main__.py", line 112, in calc_rpkm
    rpkms = vamb.parsebam.read_bamfiles(bampaths, dumpdirectory=dumpdirectory,
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/lib/python3.8/site-packages/vamb/parsebam.py", line 340, in read_bamfiles
    process.get()
  File "/storage/home/hcoda1/4/jzhao399/p-ktk3-0/miniconda3/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
ValueError: BAM file /storage/home/hcoda1/4/jzhao399/p-ktk3-0/rich_project_bio-konstantinidis/pico_new/02.megahit/pico552.bam has reference hash af5495d3741e8950a887e7803a8c1222, expected 60fdc1d5d6cb902da39e4771abb224a7. Verify that all BAM headers and FASTA headers are identical and in the same order.

Thank you,

Jianshu

**Comment by jakobnissen** [comment]
Dear @jianshu93 

So Vamb reads the FASTA file and produces a list of kmer spectra for each sequence. It then reads the BAM files and produces a list of abundances for each sequence. In order to match up every kmer spectrum with every abundance, the BAM file and the FASTA file must have the exact same sequences and in the same order.

You can check that is the case with the following commands (requires samtools installed, and an UNIX operating system):

```
$ samtools view -H MY_BAM_FILE | grep '^@SQ' | cut -f 2 | cut -b 4- | sed ';s/[ \t]*$//' > bam_headers.txt
$ grep '^>' MY_FASTA_FILE | cut -b 2- | sed ';s/[ \t]*$//' > fasta_headers.txt
$ diff bam_headers.txt fasta_headers.txt
```

If there is any output, then there are different sequences in the BAM and the FASTA file.
Please give it a try. If you see no output, then I will investigate more.

**Comment by hunglin59638** [comment]
Dear @jianshu93 
I have the same issue, and  bam_headers and fasta_headers are different.

**Comment by jakobnissen** [comment]
Closing this issue as (hopefully) resolved.

**Comment by rgtaketani** [comment]
I am running into the same issue I run the commands as @jakobnissen posted and got an infinite list of differences. I tried mapping as pasted below:

bowtie2-build megahit_out/final.contigs.fa final.contigs
bowtie2 --threads 24 -x final.contigs -1 Wob_N3_r3_1.fq.gz -2 Wob_N3_r3_2.fq.gz | \
    samtools view -bS -o Wob_N3_r3_to_sort.bam 
samtools sort Wob_N3_r3_to_sort.bam -o Wob_N3_r3.bam
samtools index Wob_N3_r3.bam

and:

minimap2 -d catalogue.mmi megahit_out/final.contigs.fa
minimap2 -t 24 -N 50 -ax sr catalogue.mmi Wob_N3_r3_1.fq.gz Wob_N3_r3_2.fq.gz > map_to_vamb.sam 
samtools view -bT megahit_out/final.contigs.fa map_to_vamb.sam > map_to_vamb.bam

and I am runnig Vamb this way:

vamb --outdir /home/data/mmeg_ngs_seqs_database/MAG/vambs --fasta /home/data/mmeg_ngs_seqs_database/MAG/megahit_out/final.contigs.fa --bamfiles /home/data/mmeg_ngs_seqs_database/MAG/map_to_vamb.bam -o C

What am I doing wrong?

Thank you in advance

**Comment by jakobnissen** [comment]
@rgtaketani Have you verified that the headers are the same in the produced BAM file and in the FASTA file? How have you done that? And which error do you get, exactly?

**Comment by rgtaketani** [comment]
Hi @jakobnissen I ran the commands below like you instructed in a previous answer:

$ samtools view -H MY_BAM_FILE | grep '^@SQ' | cut -f 2 | cut -b 4- | sed ';s/[ \t]*$//' > bam_headers.txt
$ grep '^>' MY_FASTA_FILE | cut -b 2- | sed ';s/[ \t]*$//' > fasta_headers.txt
$ diff bam_headers.txt fasta_headers.txt

I am getting this error:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/data/mmeg_ngs/rodrigo_taketani/condaenvs/vamb/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/data/mmeg_ngs/rodrigo_taketani/condaenvs/vamb/lib/python3.6/site-packages/vamb/parsebam.py", line 256, in _get_contig_rpkms
    _check_bamfile(inpath, bamfile, refhash, minlength)
  File "/home/data/mmeg_ngs/rodrigo_taketani/condaenvs/vamb/lib/python3.6/site-packages/vamb/parsebam.py", line 223, in _check_bamfile
    raise ValueError(errormsg.format(path, hash.hex(), refhash.hex()))
ValueError: BAM file /home/data/mmeg_ngs_seqs_database/MAG/map_to_vamb.bam has reference hash 4461305e38c0a70d426e75488828d7a0, expected 7a1742c002636535226811e8909da5a6. Verify that all BAM headers and FASTA headers are identical and in the same order.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/data/mmeg_ngs/rodrigo_taketani/condaenvs/vamb/bin/vamb", line 11, in <module>
    sys.exit(main())
  File "/home/data/mmeg_ngs/rodrigo_taketani/condaenvs/vamb/lib/python3.6/site-packages/vamb/__main__.py", line 476, in main
    logfile=logfile)
  File "/home/data/mmeg_ngs/rodrigo_taketani/condaenvs/vamb/lib/python3.6/site-packages/vamb/__main__.py", line 219, in run
    len(tnfs), minalignscore, minid, subprocesses, logfile)
  File "/home/data/mmeg_ngs/rodrigo_taketani/condaenvs/vamb/lib/python3.6/site-packages/vamb/__main__.py", line 120, in calc_rpkm
    subprocesses=subprocesses, logfile=logfile)
  File "/home/data/mmeg_ngs/rodrigo_taketani/condaenvs/vamb/lib/python3.6/site-packages/vamb/parsebam.py", line 343, in read_bamfiles
    process.get()
  File "/home/data/mmeg_ngs/rodrigo_taketani/condaenvs/vamb/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ValueError: BAM file /home/data/mmeg_ngs_seqs_database/MAG/map_to_vamb.bam has reference hash 4461305e38c0a70d426e75488828d7a0, expected 7a1742c002636535226811e8909da5a6. Verify that all BAM headers and FASTA headers are identical and in the same order.

Thanks again

**Comment by jakobnissen** [comment]
@rgtaketani okay, it should not be possible to have identical FASTA and BAM headers and see the error message. If that is what you see, there must be a bug in Vamb.

Try doing the hash manually in a Python interpreter like this:
```
>>> import pysam
>>> import vamb
>>> bamfile = pysam.AlignmentFile("my_bamfile.bam")
>>> vamb.vambtools._hash_refnames(f.references)
```
Do this for all BAM files. Do you get the same hash? If so, also check the FASTA file.

**Comment by rgtaketani** [comment]
I am getting this error:

>>> vamb.vambtools._hash_refnames(f.references)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'vamb.vambtools' has no attribute '_hash_refnames'

**Comment by jakobnissen** [comment]
@rgtaketani Now I'm very confused. Which VAMB version are you running? Are you seeing the function `hash_refnames` in the `vambtools.py` file?

**Comment by rgtaketani** [comment]
@jakobnissen I have version `vamb-2.1.0` installed using miniconda. I don't see the function in the file.

**Comment by jakobnissen** [comment]
@rgtaketani Try using the latest version of Vamb, installed from GitHub. I'll get onto making it installable through conda.

**Comment by rgtaketani** [comment]
Dear @jakobnissen, our IT department has installed the latest version, and it is working. Thank you for your aid in troubleshooting this.
