### ISSUE TITLE
Error in rule vamb for Snakemake workflow

### ISSUE THREAD

**Issue by nvpatin** [RasmussenLab/vamb#64]
I'm excited to test out the new and improved Vamb, and thrilled that you also made a Snakemake workflow for it. Thank you and congratulations on the publication!

When I ran it with Snakemake, it successfully got through most of the rules but I got the below error for rule vamb. I originally ran it with 20 threads, then repeated it with 2 threads to see if that was causing an issue but got the same error. 

The rule is pretty simple. I confirmed that the two input files do indeed exist (jgi_matrix/jgi.abundance.dat and contigs.flt.fna.gz). Could it be something with the "{VAMB_PARAMS} 2>{log}" component of the final command?  

Thanks,
Nastassia

[Thu Mar 25 10:45:02 2021]
rule vamb:
    input: jgi_matrix/jgi.abundance.dat, contigs.flt.fna.gz
    output: vamb/clusters.tsv, vamb/latent.npz, vamb/lengths.npz, vamb/log.txt, vamb/model.pt, vamb/mask.npz, vamb/tnf.npz
    log: log/vamb/vamb.log
    jobid: 250
    threads: 10

[Thu Mar 25 10:49:09 2021]
Error in rule vamb:
    jobid: 250
    output: vamb/clusters.tsv, vamb/latent.npz, vamb/lengths.npz, vamb/log.txt, vamb/model.pt, vamb/mask.npz, vamb/tnf.npz
    log: log/vamb/vamb.log (check log file(s) for error message)
    shell:
        rm -rf vamb;vamb --outdir vamb --fasta contigs.flt.fna.gz --jgi jgi_matrix/jgi.abundance.dat -o C -m 2000 --minfasta 500000 --outdir vamb 2>log/vamb/vamb.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

**Comment by nvpatin** [comment]
And the vamb.log file contents are here:

ERROR: Unexpected segmentation fault encountered in worker.
Traceback (most recent call last):
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 986, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/multiprocessing/connection.py", line 921, in wait
    ready = selector.select(timeout)
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 25630) is killed by signal: Segmentation fault. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/bin/vamb", line 8, in <module>
    sys.exit(main())
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 528, in main
    logfile=logfile)
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 251, in run
    dropout, cuda, batchsize, nepochs, lrate, batchsteps, logfile)
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 150, in trainvae
    logfile=logfile, modelfile=modelpath)
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/site-packages/vamb/encode.py", line 492, in trainmodel
    dataloader = self.trainepoch(dataloader, epoch, optimizer, batchsteps_set, logfile)
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/site-packages/vamb/encode.py", line 299, in trainepoch
    for depths_in, tnf_in in data_loader:
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1182, in _next_data
    idx, data = self._get_data()
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1148, in _get_data
    success, data = self._try_get_data()
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 999, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 25630) exited unexpectedly

**Comment by jakobnissen** [comment]
Wow, that looks way beyond my pay grade. Python in itself is not able to cause segmentation faults, so this means it must be a bug in the internal C or C++ implementation of Pytorch's dataloader.

I would try raising the issue at the [pytorch repository](https://github.com/pytorch/pytorch/issues). I'm closing this issue, because there is nothing we can do on the Vamb side. Sorry to not be of any help here.

**Comment by palomo11** [comment]
I had the same error: "ERROR: Unexpected segmentation fault encountered in worker". In my case, I didn't run the Snakemake workflow.

For me, the solution was to downgrade pytorch to the version 1.7.1

**Comment by nvpatin** [comment]
Thank you @palomo11, I eventually found the same solution.
