### ISSUE TITLE
error in  _load_jgi  if int(fields[1]) < minlength:

### ISSUE THREAD

**Issue by Mew233** [RasmussenLab/vamb#66]
Hi I got an issue when I run vamb with cuda...I followed the instructions described in /workflow/vamb.snake.conda.py

Traceback (most recent call last):
  File "/gpfs/ysm/project/christakis/cx79/conda_envs/vamb/bin/vamb", line 33, in <module>
    sys.exit(load_entry_point('vamb', 'console_scripts', 'vamb')())
  File "/gpfs/ysm/scratch60/christakis/cx79/vamb/vamb/__main__.py", line 530, in main
    logfile=logfile)
  File "/gpfs/ysm/scratch60/christakis/cx79/vamb/vamb/__main__.py", line 249, in run
    len(tnfs), minalignscore, minid, subprocesses, logfile)
  File "/gpfs/ysm/scratch60/christakis/cx79/vamb/vamb/__main__.py", line 101, in calc_rpkm
    rpkms = vamb.vambtools._load_jgi(file, mincontiglength, refhash)
  File "/gpfs/ysm/scratch60/christakis/cx79/vamb/vamb/vambtools.py", line 597, in _load_jgi
    if int(fields[1]) < minlength:
ValueError: invalid literal for int() with base 10: '1.04862e+06'
/var/spool/slurmd/job62741146/slurm_script: line 19: ehco: command not found

My jgi.abduance.data length is 12206262.

Thanks!

**Comment by jakobnissen** [comment]
Hello @Mew233 .

This is a bug in Vamb - I didn't know JGI could output the contig length in scientific notation. It has been fixed in the most recent commit.
Thanks for the heads-up!
