### ISSUE TITLE
Fasta catalogue smaller with 3 assemblies than with 2

### ISSUE THREAD

**Issue by nvpatin** [RasmussenLab/vamb#74]
Hi team,

I ran Vamb on two metagenomes and got some nice bins, but still not the taxa I'm most interested in. I decided to add a third metagenome to see if that helped. However, when I ran concatenate.py on the three contig fastas, the resulting catalog is MUCH smaller than the catalog generated from the original two contig fastas (38.6 Mbp with two vs 1.9 Mbp with three). I think this is also screwing up the actual binning when I try to run Vamb because I get a batch size error (see below).

Is there any reason concatenate.py would make such a small catalogue with three samples? I did not change any settings (eg minimum contig length was default for both).

Thanks,
Nastassia

(vamb) [nastassia.patin@holocron vamb_sub1M]$ vamb -o C --outdir vamb_out --jgi jgi_depth.txt --fasta catalog.fna.gz --minfasta 500000
Traceback (most recent call last):
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/bin/vamb", line 8, in <module>
    sys.exit(main())
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 528, in main
    logfile=logfile)
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 251, in run
    dropout, cuda, batchsize, nepochs, lrate, batchsteps, logfile)
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 150, in trainvae
    logfile=logfile, modelfile=modelpath)
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/site-packages/vamb/encode.py", line 466, in trainmodel
    raise ValueError('Last batch size exceeds dataset length')
ValueError: Last batch size exceeds dataset length

**Comment by jakobnissen** [comment]
Hello

This shouldn't happen, and I can't reproduce the problem on my end. Reviewing the code, I can't find the issue. It is possible for you to create a small example that reproduces the problem and send it to us?

Best regards,
Jakob

**Comment by jakobnissen** [comment]
Perhaps I should ask - which version of Vamb are you using?

**Comment by nvpatin** [comment]
I deleted an earlier post saying I had resolved the issue. I think I identified the source of the original problem, but I'm not sure how to fix it. I am using the newest version of vamb, installed with pip.

After generating three assemblies, I renamed the contigs so the headers reflected the sample of origin. In the renaming process, I think the fasta file was also linearized; ie when I check it using 'head' the screen scrolls through the first ten contigs, unlike the original file where the lines are truncated and 'head' will just show ten short lines of one contig. When the three renamed fastas were concatenated, the resulting catalog is much smaller than any of the individual three fasta files (and is back to the multi-line fasta). 

# Checking the sizes of three original contig files, and the catalog (unzipped):
(vamb) [nastassia.patin@holocron Nitrosopumilus_pacbiocontigs_renamed]$ ls -l
total 518088
-rw-r--r--. 1 nastassia.patin domain users  11070796 Jun 30 16:49 catalog.fna
-rw-r--r--. 1 nastassia.patin domain users 156956955 Jun 30 10:17 zr2760_21_sub5M_pacbio_contigs_renamed.fa
-rw-r--r--. 1 nastassia.patin domain users 180384357 Jun 30 10:20 zr2760_48_sub5M_pacbio_contigs_renamed.fa
-rw-r--r--. 1 nastassia.patin domain users 182103880 Jun 30 10:22 zr2760_69_sub5M_pacbio_contigs_renamed.fa

# Checking the first ten lines of the catalog
(vamb) [nastassia.patin@holocron Nitrosopumilus_pacbiocontigs_renamed]$ head catalog.fna 
>S1Czr2760_21C_0001
GGACAAACGGATTAACAGTCCGTTGCTCTACCAACTGAGCTATCAGGGAATAGCGAGAGA
TTATAACTAGCTATGAATTTTGAGTCAATCAAATCTTTGCTTTTATATCCCTTACTTAAT
GTTTAATTACTTTACTTACTTTATAGAGTCCTTAAGAGCTTTTCCAAACTCAGAACAAGA
GAGTAAAGTTGCATCATCAATAAGTCTCTCAAGGTCATAAGTAACGGTCTTATTTTTGAT
TGTTTTAGACATTGCATTAATGATTAAATCAGCAGCCTCTGTCCAGCCCATATGTCTGAG
CATCATTTCTGCAGAAAGAATCAAAGATGACGGGTTAACCATATCTTTACCAGCATAGCC
TGGTGCTGTTCCGTGTGTTGCCTCAAACACTCCAATGCTATCAGAAAGGTTGGCACCTGG
AGCAATTCCGATACCGCCAACTTGAGCCGCTAAGGCATCAGAAATATAGTCGCCATTAAG
GTTCAAAGTTGCAATAACAGAGTAATCTGCTGGACGAATTAAGATTTGTTGCAAAAAGGC

Could the linearization have affected the concatenate.py process by any chance?

**Comment by nvpatin** [comment]
Here is maybe a more relevant comparison (probably separate from the linearized fasta theory, but still confusing):
I assembled three metagenomes in slightly different ways, and concatenated each set of three individually to compare Vamb results. One set of assemblies was consistently larger and higher quality (more contigs > 1 Kbp, larger N50, etc); but the Vamb catalog for this set was smaller than for the lower-quality set. The numbers are:
SET 1: assembly contig sizes
Sample1: 156,956,955
Sample2: 193,226,558
Sample3: 195,846,710
SET 1 catalogue.fna: 11,100,048

SET 2: assembly contig sizes
Sample1: 134,497,307
Sample2: 160,640,332
Sample3: 156,527,058
SET 2 catalog.fna: 24,176,163

I'm wondering, what exactly happens in concatenate.py to produce such a discrepancy? I would like to use these higher-quality assemblies for binning but the catalog is just too small, and I get the following error:

(vamb) [nastassia.patin@holocron SAR11_pacbiocontigs_renamed]$ vamb -o C --outdir vamb_out --jgi jgi_depth.txt --fasta catalog.fna.gz --minfasta 500000
Traceback (most recent call last):
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/bin/vamb", line 8, in <module>
    sys.exit(main())
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 528, in main
    logfile=logfile)
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 251, in run
    dropout, cuda, batchsize, nepochs, lrate, batchsteps, logfile)
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 150, in trainvae
    logfile=logfile, modelfile=modelpath)
  File "/home/cns.local/nastassia.patin/.conda/envs/vamb/lib/python3.7/site-packages/vamb/encode.py", line 466, in trainmodel
    raise ValueError('Last batch size exceeds dataset length')
ValueError: Last batch size exceeds dataset length

**Comment by nvpatin** [comment]
One more example:
Sample1 contigs: 166 Mb
Sample2 contigs: 163 Mb
Sample3 contigs: 180 Mb
catalogue.fna: 3.4 Mb

And I get the same batch size error when I try to run Vamb using sorted & mapped reads (output of jgi_summarize_bam_contig_depths).

**Comment by jakobnissen** [comment]
There is definitely something wrong, but I'm afraid there is not much I can do from here unless I get my hands on a reproducible example. Can you perhaps take e.g. 10 contigs from each of the 3 samples, and see if Vamb behaves similarly by removing most sequences?

**Comment by jakobnissen** [comment]
The error `ValueError: Last batch size exceeds dataset length` happens when there are only a few (< 8000 or so) contigs in the catalogue. So the issue is definitely somewhere in `concatenate.py`

**Comment by nvpatin** [comment]
Hi Jakob,

As you suggested, I subsampled from each of the three assemblies, for both high- and low-quality sets (six assemblies in total; I subsampled 100 contigs from each rather than 10). Here you can see the sizes of each of subsampled assembly and the resulting Vamb catalog from each set. "TC" and "PB" refer to the two different assembly parameters used in SPAdes ("trusted contigs" vs "pacbio" for a hybrid assembly). 

(vamb) [nastassia.patin@holocron vamb_catalog_test]$ ls -l
total 248
-rw-r--r--. 1 nastassia.patin domain users  7404 Jul  1 12:50 catalog_PB.fna
-rw-r--r--. 1 nastassia.patin domain users 13903 Jul  1 12:49 catalog_TC.fna
-rw-r--r--. 1 nastassia.patin domain users 36201 Jul  1 12:46 zr2760_21_sub5M_PB_SPAdes_sub100.fa
-rw-r--r--. 1 nastassia.patin domain users 40381 Jul  1 12:41 zr2760_21_sub5M_TC_SPAdes_sub100.fa
-rw-r--r--. 1 nastassia.patin domain users 32595 Jul  1 12:48 zr2760_48_sub5M_PB_SPAdes_sub100.fa
-rw-r--r--. 1 nastassia.patin domain users 44063 Jul  1 12:43 zr2760_48_sub5M_TC_SPAdes_sub100.fa
-rw-r--r--. 1 nastassia.patin domain users 31260 Jul  1 12:48 zr2760_69_sub5M_PB_SPAdes_sub100.fa
-rw-r--r--. 1 nastassia.patin domain users 37547 Jul  1 12:44 zr2760_69_sub5M_TC_SPAdes_sub100.fa

I also attached a sheet with the stats for each of the full-sized assembly, and resulting Vamb catalog size. For both the TC and PB sets, the size of the catalog is about an order of magnitude lower than each of the individual assemblies, but for the higher-quality set (PB) the catalog is less than 50% the size of the lower-quality set (TC). 

In all 6 cases, most of the contigs are quite small (less than 1Kbp in length). Does concatenate.py do any filtering by contig size?

Thanks,
Nastassia

[vamb_catalogs_Nitroso.csv](https://github.com/RasmussenLab/vamb/files/6749785/vamb_catalogs_Nitroso.csv)

**Comment by nvpatin** [comment]
And here is how the beginning of two of those subsampled assemblies look: 

(vamb) [nastassia.patin@holocron vamb_catalog_test]$ head zr2760_21_sub5M_PB_SPAdes_sub100.fa
>zr2760_21C_0188
GTCGTGGATTTTCACCAGAAAAAGCTATGAGATTACTTAAAGGTGAAAATACTTTGCATGTAATTAATTT
ACGTGAGTTTGGTGGAAAAACTCCAGAACAAATTGAAAGGATCAAAGGAAGAATAATAGGTGATAGTGGT
AAGGCGAGAGTGAATATGGAAAATTTGAGTAACTCAGACATTACTGTTTATGGGAAAACTGTATCAATCA
TTGGTGAATCAACGCAGCTAAAACTTGCAATAGATGCTATTGAATCATTGTTAAGCGGCAGTATGCATGG
ATATGTTTACAAGAAGATTGAAGCTGGAAGACGACAGGACAAATTTGCCAGATTACAATTATGGGAAAAT
CAAGATGTCTTCTAAAGAAACTTTTACTCAGATTTCTCCAAGTGAATTTTTTTATCGTAACAGAGACCTT
GCAGGCTTTAGTAATCCAACAAGATCACTTTATACTGCAGTTCGTGAATTTGTTGAGAATTCTCTTGATG
CGTGTGATCAAAAAGGAATTTTGGCAGATGTTCACATGTCGATAAAGGCAGTTGATGCAGAAAAGCCTGA
CCCAAAACAGTATATCTTAACAGTTAGAGACAACGGTCCCGGTATAGAATCAGACCACGTTCCTCTTGCA

(vamb) [nastassia.patin@holocron vamb_catalog_test]$ head zr2760_21_sub5M_TC_SPAdes_sub100.fa 
>NODE_792_length_4222_cov_1.522075
GTGTAACTGCTTTTAACGAAAAAAATTGTGATTTAAAAGTACCAGAATTTGATAAATTTCAAGAAGAAGA
TGATAAAATTTTAAACAACTTTTCCAAAAATGTTGAAAATTTAAGAAAATTTATTGATGATCAAAAATTA
AATTCATATGTTAATTTTATAATTAATGCCTTGTTCGATGCAAATAAATACTTTAATGATCAGGAGCCTT
GGAAAAAAAAGAATGATAAAAAAAGATTAAACACTATTGTTTTTGTCGCGCTAGAATTAATAAGAAAAAT
TTCAATAATGCTTTATCCAATTATACCCTCTAGCTCAATCAAGTCATTAAGTACTTTTAATATAAATGAA
AAAGATATTTCTTTTGAAACCATTAAAGATCACAAACATTTAAAATCAAATAGCAAAATAACTAAAGTAG
AAATATTATTTATAAGAAAAATAAGGTTCATTTTTCATCTAAAATTCATTAACAAAACATCAAACCTATA
TCTTGTGACAAGTTGATTTTGTAATAATAATTTAACTCAACTGCCAAAGGATCTCATGAAGTCGAATCTA
TCTCTAACTAGCGCTTCAACTCTTTTATCTGTCTTCCTTCTTTTTACCTCAAGCTTTGCGATTGCAAATA

**Comment by liveha** [comment]
Hi, 

Sorry to hitchhike this issue tread, but I wonder if I am having a similar issue:  I have in total 24 samples that have been assembled individually (using metaSPAdes), with a contig size (n of contigs) ranging from 1,718,651 to 2,402,803. Yet, the catalogue.fna is only 880,191 contigs. 

I have tried to adjust the minimum contig size (even down to 100 bp to see it that could change anything - it did not) and check that the assemblies isnt full of short contigs (it is not). VAMB was ran as suggested in the recommended workflow. I am therefor wondering if you came to a conclusion or solution regarding this issue? 

Kind Regards, 
Live

**Comment by simonrasmu** [comment]
Dear both of you, do you have a dataset (two contig sets) available that can reproduce the result? 

Best

Simon

**Comment by nvpatin** [comment]
I attached here the three sample metagenome assemblies (subsampled to 100 contigs each) and the resulting Vamb catalog.

[binning_tests.zip](https://github.com/RasmussenLab/vamb/files/6785616/binning_tests.zip)

**Comment by jakobnissen** [comment]
@nvpatin It appears to work correctly. Of the three input files, only two contigs in total are longer than 2,000 bp, which is the default length cutoff. Running `python ~/code/vamb/src/concatenate.py output.fna zr* --nozip` produces an output file identical to the `catalog_PB.fna` that you included, and which consists of the only two contigs longer than 2,000: `S1Czr2760_21C_0188` and `S1Czr2760_21C_1287`.

If you want to keep contigs which are shorter than 2,000 bp, you can pass in the `-m` parameter. For example, to set the cutoff to 1,000: `python ~/code/vamb/src/concatenate.py output.fna zr* -m 1000`

**Comment by nvpatin** [comment]
Thanks, Jakob. This is why I asked my earlier question about any size-filtering done by concatenate.py.

I am still surprised that this set gave a worse catalog than the second set, which seemed to be lower-quality assemblies but gave a better catalog. I guess it's because my assembly stats look at # contigs > 1 Kbp, not > 2 Kbp, so the "worse" assemblies might actually have more contigs > 2 Kbp while the "better" assemblies have more contigs between 1 and 2 Kbp.

I will try changing the contig size cutoff and let you know if there are any more discrepancies!
