### ISSUE TITLE
multiprocessing util.py error

### ISSUE THREAD

**Issue by vyom84** [RasmussenLab/vamb#80]
Hi,
    I am running vamb of 81 individual assemblies. I generated bam files and then jgi depth file. I am running the following command on our grid and I am getting the following error. I don't have CUDA on our grid as there are no GPU processors. Altough, the process does generate lengths.npz, mask.npz and tnf.npz files. I am attaching the log for reference 

vamb --outdir vaout2 --fasta catalogue.fna.gz --jgi jgi_output_format.txt -o C --minfasta 200000

Traceback (most recent call last):
  File "/usr/local/devel/ANNOTATION/hsingh/anaconda3/lib/python3.8/multiprocessing/[log.txt](https://github.com/RasmussenLab/vamb/files/6881003/log.txt)", line 300, in _run_finalizers
    finalizer()
  File "/usr/local/devel/ANNOTATION/hsingh/anaconda3/lib/python3.8/multiprocessing/[log.txt](https://github.com/RasmussenLab/vamb/files/6881003/log.txt)", line 224, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/local/devel/ANNOTATION/hsingh/anaconda3/lib/python3.8/multiprocessing/util.py", line 133, in _remove_temp_dir
    rmtree(tempdir)
  File "/usr/local/devel/ANNOTATION/hsingh/anaconda3/lib/python3.8/shutil.py", line 715, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/devel/ANNOTATION/hsingh/anaconda3/lib/python3.8/shutil.py", line 672, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/local/devel/ANNOTATION/hsingh/anaconda3/lib/python3.8/shutil.py", line 670, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs00000003411b151a00164a1c'

**Comment by simonrasmu** [comment]
Hi vyom84,

This looks like a problem with your file system - are you running out of disk space or something else? If it can train until epoch 164 there shouldn't be any problem within Vamb itself that prevents it from finishing.
