### ISSUE TITLE
Separator 'C' not in sequence label

### ISSUE THREAD

**Issue by tarunaaggarwal** [RasmussenLab/vamb#87]
Hello,

I'm getting an error about a `Separator 'C' not in sequence label: 'c_000000018536'`. Does this separator 'C' get added to the catalogue of multiple fasta files? I didn't create a catalogue because I'm processing only one sample with vamb. 

Any advice on how I can fix this error? Thank you!

```
WARNING: Running Vamb on fewer than 50,000 sequences might cause overfitting of the VAE and poor results. Ideally, use 100k-5m sequences.
Traceback (most recent call last):
  File "/home/taruna/miniconda3/envs/vamb/bin/vamb", line 11, in <module>
    sys.exit(main())
  File "/home/taruna/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 476, in main
    logfile=logfile)
  File "/home/taruna/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 230, in run
    minclustersize, separator, cuda, logfile)
  File "/home/taruna/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/__main__.py", line 194, in cluster
    min_size=minclustersize, rename=False)
  File "/home/taruna/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/cluster.py", line 424, in write_clusters
    for clustername, contigs in clusters:
  File "/home/taruna/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/vambtools.py", line 434, in _binsplit_generator
    for newbinname, splitheaders in _split_bin(binname, headers, separator):
  File "/home/taruna/miniconda3/envs/vamb/lib/python3.7/site-packages/vamb/vambtools.py", line 423, in _split_bin
    raise KeyError("Separator '{}' not in sequence label: '{}'".format(separator, header))
KeyError: "Separator 'C' not in sequence label: 'c_000000018536'"
```

**Comment by tarunaaggarwal** [comment]
I forgot to look through the closed issues. Looks like someone also had this issue.
