### ISSUE TITLE
KeyError:<contig header> occuring in __main__.py in the write_fasta function.

### ISSUE THREAD

**Issue by Lamm-a** [RasmussenLab/vamb#99]
I am running into KeyErrors in (I think) this bit of `__main__.py` relating to contig names in line 211 :

```
with open(clusterspath) as file:
        clusters = vamb.vambtools.read_clusters(file)

    for cluster, contigs in clusters.items():
        size = sum(lengthof[contig] for contig in contigs) # line 211
        if size >= minfasta:
            filtered_clusters[cluster] = clusters[cluster]
```

The contig throwing the error exists in both the input assembly, and input jgi depth file and the error is happening for all runs of vamb

The error is `KeyError: 'k119_309281` or a different contig name for the other runs

Would you have any insight as to why this may be happening?

Input command: 
```
vamb --fasta /path/to/Red_500bp_filterd_dereplicated.fa --outdir /path_to/vamb_output/Red_500bp_filterd_dereplicated/vamb --jgi /path/to/Red_500bp_filterd_dereplicated_jgi.out --minfasta 200000 -m 2000 -p 40
```

Full `STDERR`stream:

```
Calculating intra contig depth variance
Output depth matrix to /home/people/robmur/prepost/final_assemblies/matriline_assembly/contig_500bp_filt/cd-hit_dereplication_output/vamb_output/Red_500bp_filterd_dereplicated/Red_500bp_filterd_dereplicated_jgi.out
Output matrix to /home/people/robmur/prepost/final_assemblies/matriline_assembly/contig_500bp_filt/cd-hit_dereplication_output/vamb_output/Red_500bp_filterd_dereplicated/Red_500bp_filterd_dereplicated_jgi.out
Opening 1 bams
Consolidating headers
Processing bam files
Thread 0 finished: Red_500bp_filterd_dereplicated_ali_sorted.bam with 172321491 reads and 99986245 readsWellMapped
Creating depth matrix file: /home/people/robmur/prepost/final_assemblies/matriline_assembly/contig_500bp_filt/cd-hit_dereplication_output/vamb_output/Red_500bp_filterd_dereplicated/Red_500bp_filterd_dereplicated_jgi.out
Closing most bam files
Closing last bam file
Finished
Traceback (most recent call last):
  File "/home/projects/ku_00014/people/robmur/programmes/miniconda3/bin/vamb", line 33, in <module>
    sys.exit(load_entry_point('vamb', 'console_scripts', 'vamb')())
  File "/home/projects/ku_00014/people/robmur/programmes/vamb/vamb/__main__.py", line 501, in main
    run(args.outdir,
  File "/home/projects/ku_00014/people/robmur/programmes/vamb/vamb/__main__.py", line 266, in run
    write_fasta(outdir, clusterspath, fastapath, contignames, contiglengths, minfasta,
  File "/home/projects/ku_00014/people/robmur/programmes/vamb/vamb/__main__.py", line 211, in write_fasta
    size = sum(lengthof[contig] for contig in contigs)
  File "/home/projects/ku_00014/people/robmur/programmes/vamb/vamb/__main__.py", line 211, in <genexpr>
    size = sum(lengthof[contig] for contig in contigs)
KeyError: 'k119_309281'
```

**Comment by simonrasmu** [comment]
Hi Lamm-a, 

I am not sure about this error. How did you generate the jgi-file? From the log it seems to be writing a new jgi-depth file which could be empty? And do you have the exact command you use?

Do you have the log-file of one of the runs?

@jakobnissen

**Comment by Lamm-a** [comment]
Hi @simonrasmu 

Sorry I should have edited. Worked out yesterday with Jakob that it was a trailing white space at the end of the contig names in the `fasta `that was not in the `bam` file

**Comment by simonrasmu** [comment]
Great!

**Comment by jakobnissen** [comment]
I'll go through and review the treatment of whitespace on the master branch to make sure this issue is addressed. For v4, which I've slowly been working on, whitespace will be handled much more stringently by checking that the FASTA identifier before any whitespace conforms to the regex in the SAM format specification. Hopyfully that way there will be no confusion between the FASTA parser, the BAM parser, and Vamb's internals

**Comment by jakobnissen** [comment]
This is now fixed on the master branch.
